version: "3.9"
services:
  perm-situ-bot:
    build: .
    container_name: perm-situ-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - TZ=Asia/Yekaterinburg
    logging:
      options:
        max-size: "10m"
        max-file: "3"
